#-----------------------------------------------------------------------------------------------------------
# 
#  Date Created: Apr 2, 2018
#  Created By  : Dingze Wang(dingzew)
#  Version     : 0.1(First)
#  Description : Insert values into below tables:
#                1. USERS
#                2. INDUSTRY
#                3. CATEGORIES
#                4. FACETS
#                5. FACET_SEEDS
#
#-----------------------------------------------------------------------------------------------------------


from __future__ import print_function
from datetime import datetime

import mysql.connector
from mysql.connector import errorcode

DB_NAME = 'jacquard_sql'

#Change the Username/Password as per the user created
cnx = mysql.connector.connect(user='pkuma1', password='password', auth_plugin='mysql_native_password')
cursor = cnx.cursor()

cnx.database = DB_NAME

today_date = datetime.now()
update_date = datetime.now()

#Inserting in USERS table
add_users = ("INSERT INTO users "
            "(user_name, user_password, is_admin, user_status, create_date, update_date) "
            "VALUES (%s, %s, %s, %s, %s, %s)")

data_users = [('anupam', 'anupam', 'T', 'A', today_date, update_date), 
              ('rebekkah', 'rebekkah', 'T', 'A', today_date, update_date), 
              ('pkuma', 'pkuma', 'T', 'A', today_date, update_date)
             ]

print("Inserting Data in Users table")
for items in data_users:
    cursor.execute(add_users, items)

cnx.commit()

#Inserting in INDUSTRY table
add_industry = ("INSERT INTO industry "
            "(industry_name, industry_description, naics_code, create_date, update_date, user_id) "
            "VALUES (%s, %s, %s, %s, %s, %s)")

data_industry = [('Hospitals', 'Hospitals', 622, today_date, update_date, 1), 
                 ('Chocolate and Confectionery Manufacturing', 'Chocolate and Confectionery Manufacturing', 31135, today_date, update_date, 1),
                 ('Bread and Bakery Product Manufacturing', 'Bread and Bakery Product Manufacturing', 31181, today_date, update_date, 1),
                 ('Snack Food Manufacturing', 'Snack Food Manufacturing', 31191, today_date, update_date, 1),
                 ('Pharmaceutical and Medicine Manufacturing', 'Pharmaceutical and Medicine Manufacturing', 32541, today_date, update_date, 1),
                 ('Dog and Cat Food Manufacturing', 'Dog and Cat Food Manufacturing', 311111, today_date, update_date, 1),
                 ('Frozen Fruit, Juice, and Vegetable Manufacturing', 'Frozen Fruit, Juice, and Vegetable Manufacturing', 311411, today_date, update_date, 1),
                 ('Fruit and Vegetable Canning', 'Fruit and Vegetable Canning', 311421, today_date, update_date, 1),
                 ('Dried and Dehydrated Food Manufacturing', 'Dried and Dehydrated Food Manufacturing', 311423, today_date, update_date, 1),
                 ('Dry, Condensed, and Evaporated Dairy Product Manufacturing', 'Dry, Condensed, and Evaporated Dairy Product Manufacturing', 311514, today_date, update_date, 1),
                 ('Seafood Product Preparation and Packaging', 'Seafood Product Preparation and Packaging', 311710, today_date, update_date, 1),
                 ('Cookie and Cracker Manufacturing', 'Cookie and Cracker Manufacturing', 311821, today_date, update_date, 1),
                 ('Roasted Nuts and Peanut Butter Manufacturing', 'Roasted Nuts and Peanut Butter Manufacturing', 311911, today_date, update_date, 1),
                 ('Soft Drink Manufacturing', 'Soft Drink Manufacturing', 312111, today_date, update_date, 1),
                 ('Paint and Coating Manufacturing', 'Paint and Coating Manufacturing', 325510, today_date, update_date, 1),
                 ('Surface Active Agent Manufacturing', 'Surface Active Agent Manufacturing', 325613, today_date, update_date, 1),
                 ('Automobile Manufacturing', 'Automobile Manufacturing', 336111, today_date, update_date, 1),
                 ('Dental Equipment and Supplies Manufacturing', 'Dental Equipment and Supplies Manufacturing', 339114, today_date, update_date, 1),
                 ('All Other Miscellaneous Manufacturing', 'All Other Miscellaneous Manufacturing', 339999, today_date, update_date, 1),
                 ('Hardware Stores', 'Hardware Stores', 444130, today_date, update_date, 1),
                 ('Supermarkets and Other Grocery (except Convenience) Stores', 'Supermarkets and Other Grocery (except Convenience) Stores', 445110, today_date, update_date, 1),
                 ('Commercial Banking', 'Commercial Banking', 522110, today_date, update_date, 1),
                 ('Insurance Agencies and Brokerages', 'Insurance Agencies and Brokerages', 524210, today_date, update_date, 1),
                 ('Marketing Research and Public Opinion Polling', 'Marketing Research and Public Opinion Polling', 541910, today_date, update_date, 1),
                 ('Sports Teams and Clubs', 'Sports Teams and Clubs', 711211, today_date, update_date, 1),
                 ('Other', 'Other', 999999, today_date, update_date, 1)
                 ]

print("Inserting Data in Industry table")
for items in data_industry:
    cursor.execute(add_industry, items)

cnx.commit()

#Inserting in CATEGORIES table
add_categories = ("INSERT INTO categories "
            "(category_name, category_description, industry_id, create_date, update_date, user_id) "
            "VALUES (%s, %s, %s, %s, %s, %s)")

data_categories = [('Hospitals', 'Hospitals', 1, today_date, update_date, 1), 
                   ('Confectionery', 'Confectionery', 2, today_date, update_date, 1),
                   ('Baking', 'Baking', 3, today_date, update_date, 1),
                   ('Snacking', 'Snacking', 4, today_date, update_date, 1),
                   ('Allergy', 'Allergy', 5, today_date, update_date, 1),
                   ('Cold and Cough', 'Cold and Cough', 5, today_date, update_date, 1),
                   ('Dog Food', 'Dog Food', 6, today_date, update_date, 1),
                   ('Cat Food', 'Cat Food', 6, today_date, update_date, 1),
                   ('Juice', 'Juice', 7, today_date, update_date, 1),
                   ('Jam and Jelly', 'Jam and Jelly', 8, today_date, update_date, 1),
                   ('Craisins', 'Craisins', 9, today_date, update_date, 1),
                   ('Protein Powder', 'Protein Powder', 10, today_date, update_date, 1),
                   ('Tuna', 'Tuna', 11, today_date, update_date, 1),
                   ('Potato Chips', 'Potato Chips', 12, today_date, update_date, 1),
                   ('Craisins', 'Craisins', 13, today_date, update_date, 1),
                   ('Peanut_Butter', 'Peanut_Butter', 13, today_date, update_date, 1),
                   ('Soda-Sweeteners', 'Soda-Sweeteners', 14, today_date, update_date, 1),
                   ('Paint', 'Paint', 15, today_date, update_date, 1),
                   ('Household Cleaners', 'Household Cleaners', 16, today_date, update_date, 1),
                   ('Automotive', 'Automotive', 17, today_date, update_date, 1),
                   ('Toothpaste', 'Toothpaste', 18, today_date, update_date, 1),
                   ('OralCare', 'OralCare', 19, today_date, update_date, 1),
                   ('Hardware Stores', 'Hardware Stores', 20, today_date, update_date, 1),
                   ('Retail', 'Retail', 21, today_date, update_date, 1),
                   ('Banking', 'Banking', 22, today_date, update_date, 1),
                   ('Financial', 'Financial', 23, today_date, update_date, 1),
                   ('Ad Agency', 'Ad Agency', 24, today_date, update_date, 1),
                   ('NHL', 'NHL', 25, today_date, update_date, 1),
                   ('Other', 'Other', 26, today_date, update_date, 1)
                  ]

print("Inserting Data in Categories table")
for items in data_categories:
    cursor.execute(add_categories, items)

cnx.commit()


#Inserting in FACETS table
add_facets = ("INSERT INTO facets "
            "(facet_name, facet_description, category_id, create_date, update_date, user_id) "
            "VALUES (%s, %s, %s, %s, %s, %s)")

data_facets = [('ingredients', 'ingredients', 2, today_date, update_date, 1), 
                ('flavours', 'flavours', 2, today_date, update_date, 1),
                ('where_purchased', 'where_purchased', 2, today_date, update_date, 1),
                ('pain_points', 'pain_points', 2, today_date, update_date, 1),
                ('demand_moments', 'demand_moments', 2, today_date, update_date, 1),
                ('day_part', 'day_part', 2, today_date, update_date, 1),
                ('time_of_day', 'time_of_day', 2, today_date, update_date, 1),
                ('ingredients', 'ingredients', 3, today_date, update_date, 1), 
                ('flavours', 'flavours', 3, today_date, update_date, 1),
                ('attributes', 'attributes', 3, today_date, update_date, 1),
                ('where_purchased', 'where_purchased', 3, today_date, update_date, 1),
                ('pain_points', 'pain_points', 3, today_date, update_date, 1),
                ('demand_moments', 'demand_moments', 3, today_date, update_date, 1),
                ('day_part', 'day_part', 3, today_date, update_date, 1),
                ('time_of_day', 'time_of_day', 3, today_date, update_date, 1),
                ('ingredients', 'ingredients', 4, today_date, update_date, 1), 
                ('flavours', 'flavours', 4, today_date, update_date, 1),
                ('attributes', 'attributes', 4, today_date, update_date, 1),
                ('where_purchased', 'where_purchased', 4, today_date, update_date, 1),
                ('pain_points', 'pain_points', 4, today_date, update_date, 1),
                ('demand_moments', 'demand_moments', 4, today_date, update_date, 1),
                ('day_part', 'day_part', 4, today_date, update_date, 1),
                ('time_of_day', 'time_of_day', 4, today_date, update_date, 1),
                ('ingredients', 'ingredients', 5, today_date, update_date, 1), 
                ('flavours', 'flavours', 5, today_date, update_date, 1),
                ('attributes', 'attributes', 5, today_date, update_date, 1),
                ('pain_points', 'pain_points', 5, today_date, update_date, 1),
                ('demand_moments', 'demand_moments', 5, today_date, update_date, 1),
                ('day_part', 'day_part', 5, today_date, update_date, 1),
                ('time_of_day', 'time_of_day', 5, today_date, update_date, 1),
                ('pain_points', 'pain_points', 6, today_date, update_date, 1),
                ('demand_moments', 'demand_moments', 6, today_date, update_date, 1),
                ('day_part', 'day_part', 6, today_date, update_date, 1),
                ('time_of_day', 'time_of_day', 6, today_date, update_date, 1),
                ('ingredients', 'ingredients', 7, today_date, update_date, 1), 
                ('flavours', 'flavours', 7, today_date, update_date, 1),
                ('attributes', 'attributes', 7, today_date, update_date, 1),
                ('where_purchased', 'where_purchased', 7, today_date, update_date, 1),
                ('pain_points', 'pain_points', 7, today_date, update_date, 1),
                ('demand_moments', 'demand_moments', 7, today_date, update_date, 1),
                ('day_part', 'day_part', 7, today_date, update_date, 1),
                ('time_of_day', 'time_of_day', 7, today_date, update_date, 1),
                ('ingredients', 'ingredients', 8, today_date, update_date, 1), 
                ('flavours', 'flavours', 8, today_date, update_date, 1),
                ('attributes', 'attributes', 8, today_date, update_date, 1),
                ('where_purchased', 'where_purchased', 8, today_date, update_date, 1),
                ('pain_points', 'pain_points', 8, today_date, update_date, 1),
                ('demand_moments', 'demand_moments', 8, today_date, update_date, 1),
                ('day_part', 'day_part', 8, today_date, update_date, 1),
                ('time_of_day', 'time_of_day', 8, today_date, update_date, 1),
                ('ingredients', 'ingredients', 9, today_date, update_date, 1), 
                ('flavours', 'flavours', 9, today_date, update_date, 1),
                ('attributes', 'attributes', 9, today_date, update_date, 1),
                ('where_purchased', 'where_purchased', 9, today_date, update_date, 1),
                ('pain_points', 'pain_points', 9, today_date, update_date, 1),
                ('demand_moments', 'demand_moments', 9, today_date, update_date, 1),
                ('day_part', 'day_part', 9, today_date, update_date, 1),
                ('time_of_day', 'time_of_day', 9, today_date, update_date, 1),
                ('ingredients', 'ingredients', 10, today_date, update_date, 1), 
                ('flavours', 'flavours', 10, today_date, update_date, 1),
                ('attributes', 'attributes', 10, today_date, update_date, 1),
                ('where_purchased', 'where_purchased', 10, today_date, update_date, 1),
                ('pain_points', 'pain_points', 10, today_date, update_date, 1),
                ('demand_moments', 'demand_moments', 10, today_date, update_date, 1),
                ('day_part', 'day_part', 10, today_date, update_date, 1),
                ('time_of_day', 'time_of_day', 10, today_date, update_date, 1),
                ('ingredients', 'ingredients', 11, today_date, update_date, 1), 
                ('flavours', 'flavours', 11, today_date, update_date, 1),
                ('attributes', 'attributes', 11, today_date, update_date, 1),
                ('where_purchased', 'where_purchased', 11, today_date, update_date, 1),
                ('pain_points', 'pain_points', 11, today_date, update_date, 1),
                ('demand_moments', 'demand_moments', 11, today_date, update_date, 1),
                ('day_part', 'day_part', 11, today_date, update_date, 1),
                ('time_of_day', 'time_of_day', 11, today_date, update_date, 1),
                ('ingredients', 'ingredients', 12, today_date, update_date, 1), 
                ('flavours', 'flavours', 12, today_date, update_date, 1),
                ('attributes', 'attributes', 12, today_date, update_date, 1),
                ('where_purchased', 'where_purchased', 12, today_date, update_date, 1),
                ('pain_points', 'pain_points', 12, today_date, update_date, 1),
                ('demand_moments', 'demand_moments', 12, today_date, update_date, 1),
                ('day_part', 'day_part', 12, today_date, update_date, 1),
                ('time_of_day', 'time_of_day', 12, today_date, update_date, 1),
                ('ingredients', 'ingredients', 13, today_date, update_date, 1), 
                ('flavours', 'flavours', 13, today_date, update_date, 1),
                ('attributes', 'attributes', 13, today_date, update_date, 1),
                ('where_purchased', 'where_purchased', 13, today_date, update_date, 1),
                ('pain_points', 'pain_points', 13, today_date, update_date, 1),
                ('demand_moments', 'demand_moments', 13, today_date, update_date, 1),
                ('day_part', 'day_part', 13, today_date, update_date, 1),
                ('time_of_day', 'time_of_day', 13, today_date, update_date, 1),
                ('ingredients', 'ingredients', 14, today_date, update_date, 1), 
                ('flavours', 'flavours', 14, today_date, update_date, 1),
                ('attributes', 'attributes', 14, today_date, update_date, 1),
                ('where_purchased', 'where_purchased', 14, today_date, update_date, 1),
                ('pain_points', 'pain_points', 14, today_date, update_date, 1),
                ('demand_moments', 'demand_moments', 14, today_date, update_date, 1),
                ('day_part', 'day_part', 14, today_date, update_date, 1),
                ('time_of_day', 'time_of_day', 14, today_date, update_date, 1),
                ('ingredients', 'ingredients', 15, today_date, update_date, 1), 
                ('flavours', 'flavours', 15, today_date, update_date, 1),
                ('attributes', 'attributes', 15, today_date, update_date, 1),
                ('where_purchased', 'where_purchased', 15, today_date, update_date, 1),
                ('pain_points', 'pain_points', 15, today_date, update_date, 1),
                ('demand_moments', 'demand_moments', 15, today_date, update_date, 1),
                ('day_part', 'day_part', 15, today_date, update_date, 1),
                ('time_of_day', 'time_of_day', 15, today_date, update_date, 1),
                ('ingredients', 'ingredients', 16, today_date, update_date, 1), 
                ('flavours', 'flavours', 16, today_date, update_date, 1),
                ('attributes', 'attributes', 16, today_date, update_date, 1),
                ('where_purchased', 'where_purchased', 16, today_date, update_date, 1),
                ('pain_points', 'pain_points', 16, today_date, update_date, 1),
                ('demand_moments', 'demand_moments', 16, today_date, update_date, 1),
                ('day_part', 'day_part', 16, today_date, update_date, 1),
                ('time_of_day', 'time_of_day', 16, today_date, update_date, 1),
                ('ingredients', 'ingredients', 17, today_date, update_date, 1), 
                ('flavours', 'flavours', 17, today_date, update_date, 1),
                ('attributes', 'attributes', 17, today_date, update_date, 1),
                ('where_purchased', 'where_purchased', 17, today_date, update_date, 1),
                ('pain_points', 'pain_points', 17, today_date, update_date, 1),
                ('demand_moments', 'demand_moments', 17, today_date, update_date, 1),
                ('day_part', 'day_part', 17, today_date, update_date, 1),
                ('time_of_day', 'time_of_day', 17, today_date, update_date, 1),
                ('where_purchased', 'where_purchased', 18, today_date, update_date, 1),
                ('pain_points', 'pain_points', 18, today_date, update_date, 1),
                ('where_purchased', 'where_purchased', 19, today_date, update_date, 1),
                ('pain_points', 'pain_points', 19, today_date, update_date, 1),
                ('where_purchased', 'where_purchased', 20, today_date, update_date, 1),
                ('pain_points', 'pain_points', 20, today_date, update_date, 1),
                ('where_purchased', 'where_purchased', 21, today_date, update_date, 1),
                ('pain_points', 'pain_points', 21, today_date, update_date, 1),
                ('where_purchased', 'where_purchased', 22, today_date, update_date, 1),
                ('pain_points', 'pain_points', 22, today_date, update_date, 1),
                ('where_purchased', 'where_purchased', 23, today_date, update_date, 1),
                ('pain_points', 'pain_points', 23, today_date, update_date, 1),
                ('pain_points', 'pain_points', 24, today_date, update_date, 1),
                ('pain_points', 'pain_points', 25, today_date, update_date, 1),
                ('pain_points', 'pain_points', 26, today_date, update_date, 1),
                ('pain_points', 'pain_points', 27, today_date, update_date, 1),
                ('pain_points', 'pain_points', 28, today_date, update_date, 1)
                ]

print("Inserting Data in Facets table")
for items in data_facets:
    cursor.execute(add_facets, items)

cnx.commit()

#Inserting in SEEDS table
add_facets_seeds = ("INSERT INTO facet_seeds "
            "(seeds_name, seeds_description, facet_id, create_date, update_date, user_id) "
            "VALUES (%s, %s, %s, %s, %s, %s)")

data_facets_seeds = [('nutmeg', 'nutmeg', 1, today_date, update_date, 1), 
                    ('lemon_juice', 'lemon_juice', 1, today_date, update_date, 1),
                    ('sesame_seeds', 'sesame_seeds', 1, today_date, update_date, 1),
                    ('lime_juice', 'lime_juice', 1, today_date, update_date, 1),
                    ('zest', 'zest', 1, today_date, update_date, 1),
                    ('ginger', 'ginger', 1, today_date, update_date, 1),
                    ('cayenne', 'cayenne', 1, today_date, update_date, 1),
                    ('mashed_banana', 'mashed_banana', 1, today_date, update_date, 1), 
                    ('maple_syrup', 'maple_syrup', 1, today_date, update_date, 1),
                    ('sliced_banana', 'sliced_banana', 1, today_date, update_date, 1),
                    ('shredded_coconut', 'shredded_coconut', 1, today_date, update_date, 1),
                    ('agave', 'agave', 1, today_date, update_date, 1),
                    ('coconut_flakes', 'coconut_flakes', 1, today_date, update_date, 1),
                    ('maple', 'maple', 1, today_date, update_date, 1),
                    ('turmeric', 'turmeric', 1, today_date, update_date, 1),
                    ('allspice', 'allspice', 1, today_date, update_date, 1), 
                    ('rosemary', 'rosemary', 1, today_date, update_date, 1),
                    ('banana_slices', 'banana_slices', 1, today_date, update_date, 1),
                    ('crasins', 'crasins', 1, today_date, update_date, 1),
                    ('coconut_sugar', 'coconut_sugar', 1, today_date, update_date, 1),
                    ('sliced_bananas', 'sliced_bananas', 1, today_date, update_date, 1),
                    ('fresh_strawberries', 'fresh_strawberries', 1, today_date, update_date, 1),
                    ('sprinkled', 'sprinkled', 1, today_date, update_date, 1),
                    ('raisins', 'raisins', 1, today_date, update_date, 1), 
                    ('caramelized', 'caramelized', 1, today_date, update_date, 1),
                    ('cinamon', 'cinamon', 1, today_date, update_date, 1),
                    ('blueberries', 'blueberries', 1, today_date, update_date, 1),
                    ('bananas', 'bananas', 1, today_date, update_date, 1),
                    ('sliced_strawberries', 'sliced_strawberries', 1, today_date, update_date, 1),
                    ('vanilla', 'vanilla', 1, today_date, update_date, 1),
                    ('cinnamon', 'cinnamon', 1, today_date, update_date, 1),
                    ('honey', 'honey', 1, today_date, update_date, 1),
                    ('paprika', 'paprika', 1, today_date, update_date, 1),
                    ('vanilla_bean', 'vanilla_bean', 2, today_date, update_date, 1),
                    ('salted_caramel', 'salted_caramel', 2, today_date, update_date, 1), 
                    ('frappuccino', 'frappuccino', 2, today_date, update_date, 1),
                    ('latte', 'latte', 2, today_date, update_date, 1),
                    ('matcha', 'matcha', 2, today_date, update_date, 1),
                    ('cashew_milk', 'cashew_milk', 2, today_date, update_date, 1),
                    ('isoflex', 'isoflex', 2, today_date, update_date, 1),
                    ('silk', 'silk', 2, today_date, update_date, 1),
                    ('questnutrition', 'questnutrition', 2, today_date, update_date, 1),
                    ('coconut_cream', 'coconut_cream', 2, today_date, update_date, 1), 
                    ('espresso', 'espresso', 2, today_date, update_date, 1),
                    ('chai', 'chai', 2, today_date, update_date, 1),
                    ('cappuccino', 'cappuccino', 2, today_date, update_date, 1),
                    ('myprotein', 'myprotein', 2, today_date, update_date, 1),
                    ('choco', 'choco', 2, today_date, update_date, 1),
                    ('snicker', 'snicker', 2, today_date, update_date, 1),
                    ('califiafarms', 'califiafarms', 2, today_date, update_date, 1),
                    ('lovemysilk', 'lovemysilk', 2, today_date, update_date, 1), 
                    ('colada', 'colada', 2, today_date, update_date, 1),
                    ('vega_team', 'vega_team', 2, today_date, update_date, 1),
                    ('banana_cream', 'banana_cream', 2, today_date, update_date, 1),
                    ('trutein', 'trutein', 2, today_date, update_date, 1),
                    ('sorbet', 'sorbet', 2, today_date, update_date, 1),
                    ('optimumnutrition', 'optimumnutrition', 2, today_date, update_date, 1),
                    ('nesquik', 'nesquik', 2, today_date, update_date, 1),
                    ('coco', 'coco', 2, today_date, update_date, 1), 
                    ('mint', 'mint', 2, today_date, update_date, 1),
                    ('blondie', 'blondie', 2, today_date, update_date, 1),
                    ('syntrax', 'syntrax', 2, today_date, update_date, 1),
                    ('maca', 'maca', 2, today_date, update_date, 1),
                    ('vanilla', 'vanilla', 2, today_date, update_date, 1),
                    ('mocha', 'mocha', 2, today_date, update_date, 1),
                    ('natural_peanut_butter', 'natural_peanut_butter', 10, today_date, update_date, 1),
                    ('sunflower_butter', 'sunflower_butter', 10, today_date, update_date, 1), 
                    ('cashew_butter', 'cashew_butter', 10, today_date, update_date, 1),
                    ('crunchy_peanut_butter', 'crunchy_peanut_butter', 10, today_date, update_date, 1),
                    ('organic_peanut_butter', 'organic_peanut_butter', 10, today_date, update_date, 1),
                    ('peanut_butter_spread', 'peanut_butter_spread', 10, today_date, update_date, 1),
                    ('chunky_peanut_butter', 'chunky_peanut_butter', 10, today_date, update_date, 1),
                    ('creamy_peanut_butter', 'creamy_peanut_butter', 10, today_date, update_date, 1),
                    ('teddie_peanut_butter', 'teddie_peanut_butter', 10, today_date, update_date, 1),
                    ('tbsp_peanut_butter', 'tbsp_peanut_butter', 10, today_date, update_date, 1), 
                    ('smooth_peanut_butter', 'smooth_peanut_butter', 10, today_date, update_date, 1),
                    ('peanut_butter_mixed', 'peanut_butter_mixed', 10, today_date, update_date, 1),
                    ('organic_almond_butter', 'organic_almond_butter', 10, today_date, update_date, 1),
                    ('natural_almond_butter', 'natural_almond_butter', 10, today_date, update_date, 1),
                    ('honey_peanut_butter', 'honey_peanut_butter', 10, today_date, update_date, 1),
                    ('pb', 'pb', 10, today_date, update_date, 1),
                    ('enoughhoney', 'enoughhoney', 10, today_date, update_date, 1),
                    ('melted_peanut_butter', 'melted_peanut_butter', 10, today_date, update_date, 1), 
                    ('nut', 'nut', 10, today_date, update_date, 1),
                    ('plain_yogurt', 'plain_yogurt', 10, today_date, update_date, 1),
                    ('real_peanut_butter', 'real_peanut_butter', 10, today_date, update_date, 1),
                    ('white_chocolate_peanut_butter', 'white_chocolate_peanut_butter', 10, today_date, update_date, 1),
                    ('powdered_peanut_butter', 'powdered_peanut_butter', 10, today_date, update_date, 1),
                    ('protein_peanut_butter', 'protein_peanut_butter', 10, today_date, update_date, 1),
                    ('peanut_butter_powder', 'peanut_butter_powder', 10, today_date, update_date, 1),
                    ('sliced', 'sliced', 10, today_date, update_date, 1), 
                    ('peanut_butter_lunch', 'peanut_butter_lunch', 10, today_date, update_date, 1),
                    ('almond_butter', 'almond_butter', 10, today_date, update_date, 1),
                    ('peanut_butter', 'peanut_butter', 10, today_date, update_date, 1),
                    ('peanut_butter_smoothie', 'peanut_butter_smoothie', 10, today_date, update_date, 1),
                    ('peanut_butter', 'peanut_butter', 10, today_date, update_date, 1),
                    ('almond_butter', 'almond_butter', 10, today_date, update_date, 1),
                    ('costco', 'costco', 3, today_date, update_date, 1),
                    ('kroger', 'kroger', 3, today_date, update_date, 1), 
                    ('store', 'store', 3, today_date, update_date, 1),
                    ('mart', 'mart', 3, today_date, update_date, 1),
                    ('wal', 'wal', 3, today_date, update_date, 1),
                    ('publix', 'publix', 3, today_date, update_date, 1),
                    ('target', 'target', 3, today_date, update_date, 1),
                    ('aldi', 'aldi', 3, today_date, update_date, 1),
                    ('walgreens', 'walgreens', 3, today_date, update_date, 1),
                    ('pharmacy', 'pharmacy', 3, today_date, update_date, 1), 
                    ('shop', 'shop', 3, today_date, update_date, 1),
                    ('supermarket', 'supermarket', 3, today_date, update_date, 1),
                    ('dusk', 'dusk', 3, today_date, update_date, 1),
                    ('cvs', 'cvs', 3, today_date, update_date, 1),
                    ('stores', 'stores', 3, today_date, update_date, 1),
                    ('grocery_stores', 'grocery_stores', 3, today_date, update_date, 1),
                    ('local_grocery_store', 'local_grocery_store', 3, today_date, update_date, 1),
                    ('checkout', 'checkout', 3, today_date, update_date, 1), 
                    ('teeter', 'teeter', 3, today_date, update_date, 1),
                    ('market', 'market', 3, today_date, update_date, 1),
                    ('coupons', 'coupons', 3, today_date, update_date, 1),
                    ('tjs', 'tjs', 3, today_date, update_date, 1),
                    ('winco', 'winco', 3, today_date, update_date, 1),
                    ('liquor', 'liquor', 3, today_date, update_date, 1),
                    ('sams', 'sams', 3, today_date, update_date, 1),
                    ('grocery', 'grocery', 3, today_date, update_date, 1),
                    ('airport', 'airport', 3, today_date, update_date, 1),
                    ('asda', 'asda', 3, today_date, update_date, 1),
                    ('trader_joes', 'trader_joes', 3, today_date, update_date, 1),
                    ('wegmans', 'wegmans', 3, today_date, update_date, 1),
                    ('walmart', 'walmart', 3, today_date, update_date, 1),
                    ('safeway', 'safeway', 3, today_date, update_date, 1),
                    ('grocery_store', 'grocery_store', 3, today_date, update_date, 1),
                    ('strange', 'strange', 4, today_date, update_date, 1),
                    ('disgusting', 'disgusting', 4, today_date, update_date, 1),
                    ('gross', 'gross', 4, today_date, update_date, 1),
                    ('bad', 'bad', 4, today_date, update_date, 1),
                    ('weird', 'weird', 4, today_date, update_date, 1),
                    ('horrible', 'horrible', 4, today_date, update_date, 1),
                    ('scary', 'scary', 4, today_date, update_date, 1),
                    ('vile', 'vile', 4, today_date, update_date, 1),
                    ('awful', 'awful', 4, today_date, update_date, 1),
                    ('terrible', 'terrible', 4, today_date, update_date, 1),
                    ('nasty', 'nasty', 4, today_date, update_date, 1),
                    ('nauseous', 'nauseous', 4, today_date, update_date, 1),
                    ('horrid', 'horrid', 4, today_date, update_date, 1),
                    ('sick', 'sick', 4, today_date, update_date, 1),
                    ('worst', 'worst', 4, today_date, update_date, 1),
                    ('swollen', 'swollen', 4, today_date, update_date, 1),
                    ('odd', 'odd', 4, today_date, update_date, 1),
                    ('danky', 'danky', 4, today_date, update_date, 1),
                    ('bland', 'bland', 4, today_date, update_date, 1),
                    ('yuck', 'yuck', 4, today_date, update_date, 1),
                    ('unpleasant', 'unpleasant', 4, today_date, update_date, 1),
                    ('icky', 'icky', 4, today_date, update_date, 1),
                    ('diarrhea', 'diarrhea', 4, today_date, update_date, 1),
                    ('itchy', 'itchy', 4, today_date, update_date, 1),
                    ('pain', 'pain', 4, today_date, update_date, 1),
                    ('ugh', 'ugh', 4, today_date, update_date, 1),
                    ('bizarre', 'bizarre', 4, today_date, update_date, 1),
                    ('funny`', 'funny', 4, today_date, update_date, 1),
                    ('tolerable', 'tolerable', 4, today_date, update_date, 1),
                    ('horrible', 'horrible', 4, today_date, update_date, 1),
                    ('terrible', 'terrible', 4, today_date, update_date, 1),
                    ('nasty', 'nasty', 4, today_date, update_date, 1),
                    ('awful', 'awful', 4, today_date, update_date, 1),
                    ('post_workout', 'post_workout', 5, today_date, update_date, 1),
                    ('cardio', 'cardio', 5, today_date, update_date, 1),
                    ('preworkout', 'preworkout', 5, today_date, update_date, 1),
                    ('workouts', 'workouts', 5, today_date, update_date, 1),
                    ('fasted', 'fasted', 5, today_date, update_date, 1),
                    ('session', 'session', 5, today_date, update_date, 1),
                    ('exercise', 'exercise', 5, today_date, update_date, 1),
                    ('refuel', 'refuel', 5, today_date, update_date, 1),
                    ('race', 'race', 5, today_date, update_date, 1),
                    ('recovery', 'recovery', 5, today_date, update_date, 1),
                    ('hiit', 'hiit', 5, today_date, update_date, 1),
                    ('bike', 'bike', 5, today_date, update_date, 1),
                    ('run', 'run', 5, today_date, update_date, 1),
                    ('yoga', 'yoga', 5, today_date, update_date, 1),
                    ('treadmill', 'treadmill', 5, today_date, update_date, 1),
                    ('protein_shake', 'protein_shake', 5, today_date, update_date, 1),
                    ('routine', 'routine', 5, today_date, update_date, 1),
                    ('elliptical', 'elliptical', 5, today_date, update_date, 1),
                    ('circuit', 'circuit', 5, today_date, update_date, 1),
                    ('stairmaster', 'stairmaster', 5, today_date, update_date, 1),
                    ('training', 'training', 5, today_date, update_date, 1),
                    ('post', 'post', 5, today_date, update_date, 1),
                    ('jog', 'jog', 5, today_date, update_date, 1),
                    ('lifting', 'lifting', 5, today_date, update_date, 1),
                    ('barre', 'barre', 5, today_date, update_date, 1),
                    ('mile', 'mile', 5, today_date, update_date, 1),
                    ('surgery', 'surgery', 5, today_date, update_date, 1),
                    ('swim`', 'swim', 5, today_date, update_date, 1),
                    ('cycling', 'cycling', 5, today_date, update_date, 1),
                    ('bedtime', 'bedtime', 5, today_date, update_date, 1),
                    ('after workout', 'after workout', 5, today_date, update_date, 1),
                    ('after gym', 'nafter gymasty', 5, today_date, update_date, 1),
                    ('pre workout', 'pre workout', 5, today_date, update_date, 1),
                    ('supper', 'supper', 6, today_date, update_date, 1),
                    ('lunch_today', 'lunch_today', 6, today_date, update_date, 1),
                    ('turkey_sandwich', 'turkey_sandwich', 6, today_date, update_date, 1),
                    ('dinner_tonight', 'dinner_tonight', 6, today_date, update_date, 1),
                    ('meal', 'meal', 6, today_date, update_date, 1),
                    ('workdays', 'workdays', 6, today_date, update_date, 1),
                    ('afternoon_snack', 'afternoon_snack', 6, today_date, update_date, 1),
                    ('snack', 'snack', 6, today_date, update_date, 1),
                    ('pear', 'pear', 6, today_date, update_date, 1),
                    ('clementine', 'clementine', 6, today_date, update_date, 1),
                    ('grilled_chicken', 'grilled_chicken', 6, today_date, update_date, 1),
                    ('salad', 'salad', 6, today_date, update_date, 1),
                    ('leftover', 'leftover', 6, today_date, update_date, 1),
                    ('dinner', 'dinner', 6, today_date, update_date, 1),
                    ('bfast', 'bfast', 6, today_date, update_date, 1),
                    ('breakfast_today', 'breakfast_today', 6, today_date, update_date, 1),
                    ('lunch', 'lunch', 6, today_date, update_date, 1),
                    ('braunschweiger', 'braunschweiger', 6, today_date, update_date, 1),
                    ('dinners', 'dinners', 6, today_date, update_date, 1),
                    ('baked_potato', 'baked_potato', 6, today_date, update_date, 1),
                    ('breakfast_sandwich', 'breakfast_sandwich', 6, today_date, update_date, 1),
                    ('chicken_salad', 'chicken_salad', 6, today_date, update_date, 1),
                    ('chicken_breast', 'chicken_breast', 6, today_date, update_date, 1),
                    ('cheese_stick', 'cheese_stick', 6, today_date, update_date, 1),
                    ('green_beans', 'green_beans', 6, today_date, update_date, 1),
                    ('meatballs', 'meatballs', 6, today_date, update_date, 1),
                    ('burrito', 'burrito', 6, today_date, update_date, 1),
                    ('dinner_time`', 'dinner_time', 6, today_date, update_date, 1),
                    ('fajitas', 'fajitas', 6, today_date, update_date, 1),
                    ('bagel', 'bagel', 6, today_date, update_date, 1),
                    ('lunch', 'lunch', 6, today_date, update_date, 1),
                    ('breakfast', 'breakfast', 6, today_date, update_date, 1),
                    ('dinner', 'dinner', 6, today_date, update_date, 1),
                    ('weekend', 'weekend', 7, today_date, update_date, 1),
                    ('afternoon', 'afternoon', 7, today_date, update_date, 1),
                    ('evening', 'evening', 7, today_date, update_date, 1),
                    ('morning_snack_time', 'morning_snack_time', 7, today_date, update_date, 1),
                    ('early_morning', 'early_morning', 7, today_date, update_date, 1),
                    ('bedtime', 'bedtime', 7, today_date, update_date, 1),
                    ('session', 'session', 7, today_date, update_date, 1),
                    ('hours', 'hours', 7, today_date, update_date, 1),
                    ('nap', 'nap', 7, today_date, update_date, 1),
                    ('night', 'night', 7, today_date, update_date, 1),
                    ('day', 'day', 7, today_date, update_date, 1),
                    ('eating_breakfast', 'eating_breakfast', 7, today_date, update_date, 1),
                    ('sunrise', 'sunrise', 7, today_date, update_date, 1),
                    ('nights', 'nights', 7, today_date, update_date, 1),
                    ('nite', 'nite', 7, today_date, update_date, 1),
                    ('tonight', 'tonight', 7, today_date, update_date, 1),
                    ('supper', 'supper', 7, today_date, update_date, 1),
                    ('evenings', 'evenings', 7, today_date, update_date, 1),
                    ('dinner', 'dinner', 7, today_date, update_date, 1),
                    ('midday', 'midday', 7, today_date, update_date, 1),
                    ('heading', 'heading', 7, today_date, update_date, 1),
                    ('tuesday', 'tuesday', 7, today_date, update_date, 1),
                    ('morning', 'morning', 7, today_date, update_date, 1),
                    ('afternoons', 'afternoons', 7, today_date, update_date, 1),
                    ('sunset', 'sunset', 7, today_date, update_date, 1),
                    ('small_snack', 'small_snack', 7, today_date, update_date, 1),
                    ('deadline', 'deadline', 7, today_date, update_date, 1),
                    ('came_home`', 'came_home', 7, today_date, update_date, 1),
                    ('couple_hours', 'couple_hours', 7, today_date, update_date, 1),
                    ('rain', 'rain', 7, today_date, update_date, 1),
                    ('morning', 'morning', 7, today_date, update_date, 1),
                    ('afternoon', 'afternoon', 7, today_date, update_date, 1),
                    ('evening', 'evening', 7, today_date, update_date, 1),
                    ('late night', 'late night', 7, today_date, update_date, 1)
                    ]

print("Inserting Data in Facets Seeds table")
for items in data_facets_seeds:
    cursor.execute(add_facets_seeds, items)

cnx.commit()

#Closing the Database connection
cursor.close()
cnx.close()